### ISSUE TITLE
Use Telescope `file_ignore_patterns` to filter `.git`

### ISSUE THREAD

**Issue by tobias-edwards** [skbolton/titan#10]
I noticed you're extending the `find_command` to ignore `.git` (in order to show hidden files while respecting `.gitignore` and to also exclude `.git` which isn't typically included in `.gitignore`):

https://github.com/skbolton/titan/blob/d37c0178c41652191285fe031ca89ee0568c3bf5/nvim/nvim/lua/fuzzy.lua#L48

This could be achieved more semantically via `telescope.defaults.file_ignore_patterns`:

```lua
telescope.setup({
  defaults = {
    file_ignore_patterns = {".git"},
    ...
  },
  ...
})
```

You may then be able to express your `find_command` using the supported boolean flags?

**Comment by skbolton** [comment]
Thanks for the tip. I have moved to nixos and a different dotfiles repo but I'll bemlooking into implementing this over there.
