### ISSUE TITLE
Unknown functions in lightline tabbar

### ISSUE THREAD

**Issue by ecklf** [skbolton/titan#2]
Hi there,

where are those functions defined, does a plugin handle this?
 https://github.com/skbolton/titan/blob/53f5bdce163191c5a0b5341cceaabd0d1f7d9ed2/states/nvim/nvim/tab-line.vim#L53
```
E117: Unknown function: Col_num
E117: Unknown function: Line_percent
E15: Invalid expression: Line_percent()
```

**Comment by skbolton** [comment]
Sorry github never notified me on this one. I hope you figured it out. If not then the functions that this file references are also in that file at the top. If you copy part of my bar config be sure to copy the functions from up above that correspond to it. If you have more questions open another issue and I hope that github notifies me better in the future.
