### ISSUE TITLE
How to adapt scratchpads to multiscreen!

### ISSUE THREAD

**Issue by jczhang02** [skbolton/titan#9]
I feel fuzzy that can your scratchpad config make effect when I am using three screen like this:
![image](https://user-images.githubusercontent.com/44057232/144252817-f576569b-e72b-4365-a0ee-a19477057280.png)

**Comment by skbolton** [comment]
The fix that I put in place in my dotfiles would only apply in your layout if you have scratchpads that animate down, or left on DP-0. If they animate up or right you shouldn’t need my solution.

**Comment by jczhang02** [comment]
So, your answer means that i can't make this config adapt to my screen layout ? 
I think issue happened when call 'scratchpad.init', it remenber the screen geometry of screen.

**Comment by skbolton** [comment]
Do you have scratchpads that animate down?

**Comment by jczhang02** [comment]
what it means ?

**Comment by skbolton** [comment]
Oh I think I get where the disconnect is. I only ever use scratchpads on my main monitor. Do you want them on all monitors?

**Comment by jczhang02** [comment]
Yes, maybe sometimes i need use it on all monitors

**Comment by skbolton** [comment]
You’ll have to adapt my scripting then. I use several computers and wanted the scratchpads to always be positioned nicely on each setup. My compromise was that I would always launch from the primary monitor.
